# Generated by Django 5.2 on 2025-05-13 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('handled_by', models.CharField(choices=[('sa', 'SA'), ('ppk', 'PPK')], default='sa')),
                ('is_available', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_payment', models.BooleanField(default=False)),
                ('requires_documents', models.BooleanField(default=False)),
                ('features', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='VenueAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_availability',
                'unique_together': {('venue', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
