# Generated by Django 5.2 on 2025-05-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='department',
        ),
        migrations.AddField(
            model_name='venue',
            name='handled_by',
            field=models.CharField(choices=[('sa', 'SA'), ('ppk', 'PPK')], default='sa'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
