# Generated by Django 5.2 on 2025-06-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='required_document_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
