# Generated by Django 5.2 on 2025-05-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='room_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
