# Generated by Django 5.2 on 2025-05-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
