# Generated by Django 5.2 on 2025-05-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='room_number',
            new_name='RoomNumber',
        ),
    ]
