# Generated by Django 5.2 on 2025-04-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bio_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default_profilepic.jpg', upload_to='profile_pics/'),
        ),
    ]
