# Generated by Django 5.2 on 2025-04-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='userprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='userprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
