# Generated by Django 5.2 on 2025-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
