# Generated by Django 5.2 on 2025-06-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='setup_time',
        ),
        migrations.RemoveField(
            model_name='eventdetail',
            name='teardown_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('documents_pending', 'Documents Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('documents_pending', 'Documents Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='previous_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('documents_pending', 'Documents Pending')], max_length=20),
        ),
    ]
