# Generated by Django 5.2 on 2025-05-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'General Feedback'), ('rejection', 'Rejection Reason'), ('approval', 'Approval Notes'), ('requirement', 'Additional Requirements'), ('note', 'Additional Notes')], default='general', max_length=50),
        ),
    ]
